name: ITrafficMonitorForMac

options:
  minimumXcodeGenVersion: 2.44.0
  createIntermediateGroups: true
  developmentLanguage: en

configs:
  Debug: debug
  Release: release

settings:
  base:
    PRODUCT_NAME: ITraffic
    MACOSX_DEPLOYMENT_TARGET: "14.0"

targets:
  ITrafficMonitorForMac:
    type: application
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - path: ITrafficMonitorForMac
        excludes:
          - Info.plist
          - ITrafficMonitorForMac.entitlements
          - Assets.xcassets
          - "Preview Content"
          - Base.lproj
          - NetworkFilter
      - path: ITrafficMonitorForMac/NetworkFilter/Shared
      - path: ITrafficMonitorForMac/Assets.xcassets
        buildPhase: resources
      - path: ITrafficMonitorForMac/Preview Content/Preview Assets.xcassets
        buildPhase: resources
      - path: ITrafficMonitorForMac/Base.lproj/Main.storyboard
        buildPhase: resources
    settings:
      base:
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        CODE_SIGN_STYLE: Automatic
        COMBINE_HIDPI_IMAGES: YES
        CURRENT_PROJECT_VERSION: 8
        DEVELOPMENT_ASSET_PATHS: "\"ITrafficMonitorForMac/Preview Content\""
        ENABLE_HARDENED_RUNTIME: YES
        ENABLE_PREVIEWS: YES
        INFOPLIST_FILE: ITrafficMonitorForMac/Info.plist
        LD_RUNPATH_SEARCH_PATHS:
          - "$(inherited)"
          - "@executable_path/../Frameworks"
        MARKETING_VERSION: 0.3.0
        PRODUCT_BUNDLE_IDENTIFIER: com.foamzou.ITrafficMonitorForMac
        OTHER_LDFLAGS:
          - "-lsqlite3"
        SWIFT_VERSION: 5.0

  TrafficFilterDataProvider:
    type: system-extension
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - path: ITrafficMonitorForMac/NetworkFilter/DataProvider
      - path: ITrafficMonitorForMac/NetworkFilter/Shared
    dependencies:
      - target: TrafficFilterDataProvider
      - target: TrafficFilterControlProvider
    settings:
      base:
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_ENTITLEMENTS: ITrafficMonitorForMac/NetworkFilter/DataProvider/TrafficFilterDataProvider.entitlements
        INFOPLIST_FILE: ITrafficMonitorForMac/NetworkFilter/DataProvider/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.foamzou.ITrafficMonitorForMac.TrafficFilterDataProvider
        SWIFT_VERSION: 5.0

  TrafficFilterControlProvider:
    type: app-extension
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - path: ITrafficMonitorForMac/NetworkFilter/ControlProvider
      - path: ITrafficMonitorForMac/NetworkFilter/Shared
    settings:
      base:
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_ENTITLEMENTS: ITrafficMonitorForMac/NetworkFilter/ControlProvider/TrafficFilterControlProvider.entitlements
        INFOPLIST_FILE: ITrafficMonitorForMac/NetworkFilter/ControlProvider/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.foamzou.ITrafficMonitorForMac.TrafficFilterControlProvider
        SWIFT_VERSION: 5.0

  ITrafficMonitorForMacTests:
    type: bundle.unit-test
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - path: ITrafficMonitorForMacTests
    dependencies:
      - target: ITrafficMonitorForMac
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: com.foamzou.ITrafficMonitorForMacTests
        PRODUCT_NAME: ITrafficMonitorForMacTests
        SWIFT_MODULE_NAME: ITrafficMonitorForMacTests
        BUNDLE_LOADER: "$(TEST_HOST)"
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/ITraffic.app/Contents/MacOS/ITraffic"
        SWIFT_VERSION: 5.0

schemes:
  ITrafficMonitorForMac:
    build:
      targets:
        ITrafficMonitorForMac: all
    run:
      config: Debug
    analyze:
      config: Debug
    profile:
      config: Release
    archive:
      config: Release
    test:
      config: Debug
      targets:
        - ITrafficMonitorForMacTests
